%% SNHT Wall Animation Script
% David Olson, 01 July 2021

% Start Fresh
close all
clear all
clc

% Example Plane Points
A = [2; 1; 0];
B = [2; 2; 1];
C = [2; 3; 0];
xyz = [A, B, C];
color_str = ['r', 'g', 'b'];

% Plot Example Starting Point
figure(1)
hold on
plot_frame(eye(3), zeros(3,1), 'c', 'k');
patch([2 2 2 2], [-1 4 4 -1], [2 2 -1 -1], [1 1 1 1])
grid on
axis equal
view([-131 30])
title('SNHT Wall Starting example')
xlabel('X')
ylabel('Y')
zlabel('Z')
xlim([-0.5, 3.5])
ylim([-1.5, 4.5])
zlim([-1.5, 2.5])
pause

plot3(A(1), A(2), A(3), 'r*', 'LineWidth', 5)
plot3(B(1), B(2), B(3), 'g*', 'LineWidth', 5)
plot3(C(1), C(2), C(3), 'b*', 'LineWidth', 5)
text(A(1)-0.1, A(2), A(3)+0.2, 'A')
text(B(1)-0.1, B(2), B(3)+0.2, 'B')
text(C(1)-0.1, C(2), C(3)+0.2, 'C')
quiver3(2, 2, 0, -1, 0, 0, 'Color', 'k', 'LineWidth', 1)
text(1.5, 2.25, -0.1, 'n') 

hold off

% Open Figure Window 2
figure(2)
figure(3)

% Pause Script
disp('Press any key to continue')
pause

% Define the Hough Search Space
psi = (-90 : 10 : 90) * pi/180;

% Begin Animation
for k = 1 : 3
    for ii = 1 : length(psi)
        
        % Create Values for Surface Normal Animation
        uwv = rotate_z(psi(ii)) * [1; 0; 0];
        
        % Example Plot Number 1
        figure(2)
        hold on
        plot_frame(eye(3), zeros(3,1), 'c', 'k');
        patch([2 2 2 2], [-1 4 4 -1], [2 2 -1 -1], [1 1 1 1])
        grid on
        axis equal
        view([-131 30])
        xlabel('X')
        ylabel('Y')
        zlabel('Z')
        xlim([-0.5, 3.5])
        ylim([-1.5, 4.5])
        zlim([-1.5, 2.5])
        plot3(A(1), A(2), A(3), 'r*', 'LineWidth', 5)
        plot3(B(1), B(2), B(3), 'g*', 'LineWidth', 5)
        plot3(C(1), C(2), C(3), 'b*', 'LineWidth', 5)
        text(A(1)-0.1, A(2), A(3)+0.2, 'A')
        text(B(1)-0.1, B(2), B(3)+0.2, 'B')
        text(C(1)-0.1, C(2), C(3)+0.2, 'C')
        quiver3(2, 2, 0, -1, 0, 0, 'Color', 'k', 'LineWidth', 1)
        text(1.5, 2.25, -0.1, 'n')  
        quiver3(xyz(1,k), xyz(2,k), xyz(3,k), ...
               -uwv(1), -uwv(2), uwv(3), ...
               'Color', color_str(k), 'LineWidth', 1)
        title(['Test Surface Normal Vector:  ' ...
            '    \psi = ', num2str(psi(ii)*180/pi), '\circ'])
        hold off
        
        % Convert into the Hough Space
        rho_calc(ii,k) = cos(psi(ii))*xyz(1,k) - sin(psi(ii))*xyz(2,k);
        
        if (k ==1) && (ii == 1)
            disp('starting in 5 sec')
            pause(1)
            disp('starting in 4 sec')
            pause(1)
            disp('starting in 3 sec')
            pause(1)
            disp('starting in 2 sec')
            pause(1)
            disp('starting in 1 sec')
            pause(1)
        end
        
        % Example Plot 2
        figure(3)
        hold on
        cs = [color_str(k), '*'];
        plot(psi(ii) * 180/pi, rho_calc(ii,k), cs)
        title('SNHT sinusoids generated by \psi and \rho')
        xlabel('\psi (\circ)')
        ylabel('\rho')
        xlim([psi(1) psi(end)] .* 180/pi)
        ylim([-4 4])
        grid on
        hold off
        
        % Pause Animation
        if (k == 1)
            pause_time = 1;
        else
            pause_time = 0.5;
        end
        pause(pause_time)
        
%         % Clear Plot 2
%         if ((k ~= 3) || (psi(end) ~= psi(ii)))
%             clf(2)
%         end
        
    end
    
end